# Generated by Django 5.0 on 2024-10-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='dishing_up_time',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='preparation_time',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='total_recipe_time',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
